service: docs-classifier

provider:
  name: aws
  runtime: nodejs12.x
  region : us-east-2  

functions:
  classifier:
    handler: handler.handle
    layers:
      - arn:aws:lambda:us-east-2:601408256835:layer:infra-docs:2
    events:
      - httpApi:
          path: /classifier
          method: get
plugins:
  - serverless-offline # Needed to run & debug locally