service: docs-text-extract

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region : ${env:AWS_REGION}
  environment:
    LAYER_INFRA_DOCS: ${env:LAYER_INFRA_DOCS}
    PATH_LAYER: ${env:PATH_LAYER}

functions:
  text-extract:
    handler: handler.handle
    layers:
      - ${env:LAYER_INFRA_DOCS}
    events:
      - httpApi:
          path: /extract
          method: get


plugins:
  - serverless-offline # Needed to run & debug locally